minimumScore: 50
base_frame: base_footprint
map_frame: map
odom_frame: odom
map_update_interval: 4.0 <!--CHANGED!-->
maxUrange: 4.4
sigma: 0.05
kernelSize: 1
lstep: 0.02
astep: 0.05
iterations: 8
lsigma: 0.075
ogain: 3.0
lskip: 0
srr: 0.08
srt: 0.1
str: 0.08
stt: 0.1
linearUpdate: 0.1
angularUpdate: 0.3
temporalUpdate: 8.0
resampleThreshold: 0.5
particles: 260
xmin: -4.0
ymin: -4.0
xmax: 4.0
ymax: 4.0
delta: 0.04
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
transform_publish_period: 0.05
occ_thresh: 0.25
maxRange: 4.7
