#initial_pose_x" default="0.0
#initial_pose_y" default="0.0
#initial_pose_a" default="0.0
#odom_model_type: "omni"
use_map_topic: True
first_map_only: True
gui_publish_rate: 1.0
min_particles: 500
max_particles: 4000
kld_err: 0.04
kld_z: 0.99
odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.8
odom_alpha4: 0.2
odom_alpha5: 0.1
laser_max_range: 4.0
laser_max_beams: 30
laser_z_hit: 0.5
laser_z_short: 0.2
laser_z_max: 0.05
laser_z_rand: 0.5
laser_sigma_hit: 0.05
laser_lambda_short: 0.1
laser_model_type: "likelihood_field"
laser_likelihood_max_dist: 2.0
update_min_d: 0.2
update_min_a: 0.5
global_frame_id: "map"
base_frame_id: "base_footprint"
odom_frame_id: "odom"
resample_interval: 1
transform_tolerance: 0.04
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1
initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
